// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc692.OffSeason2014.subsystems;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.SpeedController;
import org.usfirst.frc692.OffSeason2014.RobotMap;
import org.usfirst.frc692.OffSeason2014.commands.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class Gatherer extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController gathererVictor = RobotMap.gatherergathererVictor;
    DoubleSolenoid gathererPiston = RobotMap.gatherergathererPiston;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void gatherMotorForward() {
        gathererVictor.set(1.0);
        //gatherer moves clock-wise
        //ND 11/20/14
    }
    
    public void gatherMotorReverse() {
        gathererVictor.set(-1.0);
        //gatherer moves counter clock-wise
        //ND 11/20/14
    }
    
    public void gathererUp() {
        gathererPiston.set(DoubleSolenoid.Value.kReverse);
    }
    //gatherer goes up
    //ND 11/10/14
    
    public void gathererDown() {
        gathererPiston.set(DoubleSolenoid.Value.kForward);
    }
    //gatherer goes down
    //ND 11/10/14
    
    public void takeOperatorJoystickValue(double x){
        gathererVictor.set(x);
    }
    //gatherer is set in the variable x
    //ND 11/10/14
    
}
